"""Interactive viewer for test examples generated by test.py.

For each example, toggles between the reverberant input spectrogram and the
dereverbed output spectrogram. Click buttons to switch views, navigate
examples, and play back the audio.

On WSL, playback uses powershell.exe + Media.SoundPlayer (no Linux audio stack
required). Elsewhere it falls back to sounddevice if available.
"""
import argparse
import glob
import os
import re
import shutil
import subprocess

import numpy as np
import soundfile as sf
import matplotlib.pyplot as plt
from matplotlib.widgets import Button


def _is_wsl():
    try:
        with open('/proc/version') as f:
            return 'microsoft' in f.read().lower()
    except OSError:
        return False


class Player:
    """Plays wav files. Uses powershell.exe on WSL, sounddevice otherwise."""

    def __init__(self):
        self.proc = None
        self.sd = None
        self.use_powershell = _is_wsl() and shutil.which('powershell.exe') is not None
        if not self.use_powershell:
            try:
                import sounddevice as sd
                self.sd = sd
            except ImportError:
                pass

    def stop(self):
        if self.proc is not None and self.proc.poll() is None:
            self.proc.terminate()
        self.proc = None
        if self.sd is not None:
            self.sd.stop()

    def play(self, wav_path, audio=None, sr=None):
        self.stop()
        if self.use_powershell:
            win_path = subprocess.check_output(
                ['wslpath', '-w', os.path.abspath(wav_path)]).decode().strip()
            ps = f'(New-Object Media.SoundPlayer "{win_path}").PlaySync()'
            self.proc = subprocess.Popen(
                ['powershell.exe', '-NoProfile', '-Command', ps],
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            return
        if self.sd is not None and audio is not None:
            try:
                self.sd.play(audio, sr)
            except Exception as e:
                print(f'sounddevice playback failed: {e}')
            return
        print('No audio backend available (install sounddevice or run on WSL).')


def spectrogram_db(x, frame_length=512, frame_step=128, sr=16000):
    # Matches train.py's STFT layer: right-pad, periodic Hann, drop DC bin.
    pad = frame_length - frame_step
    xp = np.concatenate([x, np.zeros(pad)])
    n = np.arange(frame_length)
    win = 0.5 - 0.5 * np.cos(2 * np.pi * n / frame_length)
    n_frames = 1 + (len(xp) - frame_length) // frame_step
    frames = np.stack([xp[i * frame_step:i * frame_step + frame_length] * win
                       for i in range(n_frames)])
    Z = np.fft.rfft(frames, n=frame_length, axis=-1)[:, 1:]
    return (20 * np.log10(np.abs(Z) + 1e-6)).T


def _batch_index(example_dir):
    """Parse the batch id from directory names of the form `example_b{N}_{k}`."""
    m = re.search(r'b(\d+)_\d+$', os.path.basename(example_dir))
    return int(m.group(1)) if m else -1


def find_examples(root):
    """Return a list of (batch_idx, dir, input_wav, output_wav, target_wav) tuples."""
    out = []
    for d in sorted(glob.glob(os.path.join(root, 'example_*'))):
        in_wav = os.path.join(d, 'input.wav')
        tgt_wav = os.path.join(d, 'target.wav')
        preds = sorted(p for p in glob.glob(os.path.join(d, '*.wav'))
                       if os.path.basename(p) not in ('input.wav', 'target.wav'))
        if os.path.exists(in_wav) and preds:
            out.append((_batch_index(d), d, in_wav, preds[0],
                        tgt_wav if os.path.exists(tgt_wav) else None))
    return out


class Viewer:
    def __init__(self, examples):
        if not examples:
            raise SystemExit('No examples found. Run test.py first.')
        self.examples = examples
        self.idx = 0
        self.view = 'input'  # one of: 'input', 'output', 'target'
        self.player = Player()

        plt.rcParams.update({
            'font.size': 8,
            'axes.titlesize': 9,
            'axes.labelsize': 8,
            'xtick.labelsize': 7,
            'ytick.labelsize': 7,
        })

        self.fig = plt.figure(figsize=(12, 5))
        # explicit positions so we can center buttons under the spectrogram
        # alone, ignoring the colorbar to its right.
        spec_left, spec_right = 0.08, 0.86
        spec_bottom, spec_top = 0.30, 0.92
        self.ax = self.fig.add_axes(
            [spec_left, spec_bottom, spec_right - spec_left, spec_top - spec_bottom])
        self.cax = self.fig.add_axes([spec_right + 0.015, spec_bottom, 0.015, spec_top - spec_bottom])
        self.cbar = None

        # 4 columns, equal width + equal spacing, centered under the spectrogram.
        col_w, col_h = 0.10, 0.05
        gap = 0.04
        n_cols = 4
        total = n_cols * col_w + (n_cols - 1) * gap
        spec_center = (spec_left + spec_right) / 2
        x0 = spec_center - total / 2
        cols = [x0 + i * (col_w + gap) for i in range(n_cols)]
        y_top, y_bot = 0.12, 0.04

        ax_next = self.fig.add_axes([cols[0], y_top, col_w, col_h])
        ax_prev = self.fig.add_axes([cols[0], y_bot, col_w, col_h])
        self.btn_prev = Button(ax_prev, '◀ Prev')
        self.btn_next = Button(ax_next, 'Next ▶')
        self.btn_prev.on_clicked(lambda _: self.step(-1))
        self.btn_next.on_clicked(lambda _: self.step(+1))

        ax_play_in = self.fig.add_axes([cols[1], y_top, col_w, col_h])
        ax_play_out = self.fig.add_axes([cols[2], y_top, col_w, col_h])
        ax_play_tgt = self.fig.add_axes([cols[3], y_top, col_w, col_h])
        ax_show_in = self.fig.add_axes([cols[1], y_bot, col_w, col_h])
        ax_show_out = self.fig.add_axes([cols[2], y_bot, col_w, col_h])
        ax_show_tgt = self.fig.add_axes([cols[3], y_bot, col_w, col_h])

        self.btn_in = Button(ax_play_in, '▶ Play input')
        self.btn_out = Button(ax_play_out, '▶ Play output')
        self.btn_tgt = Button(ax_play_tgt, '▶ Play target')
        self.btn_show_in = Button(ax_show_in, 'Show input')
        self.btn_show_out = Button(ax_show_out, 'Show output')
        self.btn_show_tgt = Button(ax_show_tgt, 'Show target')
        for b in (self.btn_prev, self.btn_next, self.btn_in, self.btn_out, self.btn_tgt,
                  self.btn_show_in, self.btn_show_out, self.btn_show_tgt):
            b.label.set_fontsize(8)

        self.btn_in.on_clicked(lambda _: self.player.play(self.in_wav, self.input_audio, self.sr))
        self.btn_out.on_clicked(lambda _: self.player.play(self.out_wav, self.output_audio, self.sr))
        self.btn_tgt.on_clicked(
            lambda _: self.target_audio is not None
            and self.player.play(self.tgt_wav, self.target_audio, self.sr))
        self.btn_show_in.on_clicked(lambda _: self.show('input'))
        self.btn_show_out.on_clicked(lambda _: self.show('output'))
        self.btn_show_tgt.on_clicked(
            lambda _: self.target_spec is not None and self.show('target'))

        self.load()

    def load(self):
        self.batch_idx, _, self.in_wav, self.out_wav, self.tgt_wav = self.examples[self.idx]
        self.input_audio, sr = sf.read(self.in_wav)
        self.output_audio, _ = sf.read(self.out_wav)
        if self.tgt_wav is not None:
            self.target_audio, _ = sf.read(self.tgt_wav)
        else:
            self.target_audio = None
        lens = [len(self.input_audio), len(self.output_audio)]
        if self.target_audio is not None:
            lens.append(len(self.target_audio))
        n = min(lens)
        self.input_audio = self.input_audio[:n]
        self.output_audio = self.output_audio[:n]
        if self.target_audio is not None:
            self.target_audio = self.target_audio[:n]
        self.sr = sr

        self.input_spec = spectrogram_db(self.input_audio, sr=sr)
        self.output_spec = spectrogram_db(self.output_audio, sr=sr)
        self.target_spec = (spectrogram_db(self.target_audio, sr=sr)
                            if self.target_audio is not None else None)
        # align shapes (stft padding may leave a one-frame difference)
        shapes = [self.input_spec.shape[1], self.output_spec.shape[1]]
        if self.target_spec is not None:
            shapes.append(self.target_spec.shape[1])
        nt = min(shapes)
        self.input_spec = self.input_spec[:, :nt]
        self.output_spec = self.output_spec[:, :nt]
        if self.target_spec is not None:
            self.target_spec = self.target_spec[:, :nt]

        nfreq, nframes = self.input_spec.shape
        vmin, vmax = -40, 40
        extent = [0, nframes, 0, nfreq]

        self.ax.clear()
        self.ax.set_xlabel('time frame')
        self.ax.set_ylabel('freq bin')

        self.im = self.ax.imshow(self._current_spec(), vmin=vmin, vmax=vmax,
                                 origin='lower', aspect='auto', extent=extent)
        if self.cbar is None:
            self.cbar = self.fig.colorbar(self.im, cax=self.cax, label='dB')
        else:
            self.cbar.update_normal(self.im)
        self._update_title()
        self.fig.canvas.draw_idle()

    def _current_spec(self):
        if self.view == 'input':
            return self.input_spec
        if self.view == 'output':
            return self.output_spec
        return self.target_spec if self.target_spec is not None else self.input_spec

    def _view_label(self):
        return {'input': 'input (reverberant)',
                'output': 'output (dereverbed)',
                'target': 'target (clean)'}[self.view]

    def _update_title(self):
        self.ax.set_title(
            f'batch {self.batch_idx}   '
            f'({self.idx + 1} / {len(self.examples)})   —   viewing: {self._view_label()}')

    def show(self, view):
        self.view = view
        self.im.set_data(self._current_spec())
        self._update_title()
        self.fig.canvas.draw_idle()

    def step(self, delta):
        self.player.stop()
        self.idx = (self.idx + delta) % len(self.examples)
        self.load()


if __name__ == '__main__':
    p = argparse.ArgumentParser()
    p.add_argument('--dir', default='./demo',
                   help='Directory containing example_*/ subdirs written by test.py')
    args = p.parse_args()
    Viewer(find_examples(args.dir))
    plt.show()
